"""add_sentiment_with_check

Revision ID: 08dcffea9906
Revises: b2e5392828c5
Create Date: 2026-05-25 15:59:58.211644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08dcffea9906'
down_revision: Union[str, Sequence[str], None] = 'b2e5392828c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('sentiment_trust', sa.Integer(), nullable=False))
    op.add_column('movies', sa.Column('sentiment', sa.Text(), nullable=False))
    op.drop_column('movies', 'sentiment_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('sentiment_score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('movies', 'sentiment')
    op.drop_column('movies', 'sentiment_trust')
    # ### end Alembic commands ###
