"""adicionando is profile complete na users

Revision ID: 125d822952ba
Revises: 99917e9fd0b7
Create Date: 2026-06-10 23:18:41.588767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '125d822952ba'
down_revision: Union[str, Sequence[str], None] = '99917e9fd0b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_profile_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_profile_complete')
    # ### end Alembic commands ###
