"""adicao da coluna reviews

Revision ID: 58f7b7831ffa
Revises: 7d83f438f70a
Create Date: 2026-05-30 11:33:25.792215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f7b7831ffa'
down_revision: Union[str, Sequence[str], None] = '7d83f438f70a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('has_reviews', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'has_reviews')
    # ### end Alembic commands ###
