"""adicionando constraint na tabela favorites

Revision ID: 99917e9fd0b7
Revises: 58f7b7831ffa
Create Date: 2026-05-31 21:05:26.001579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99917e9fd0b7'
down_revision: Union[str, Sequence[str], None] = '58f7b7831ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'favorites', ['user_id', 'movie_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorites', type_='unique')
    # ### end Alembic commands ###
