"""adicionando is profile complete na users with nullable

Revision ID: c09ead0f121b
Revises: bfc085b2df32
Create Date: 2026-06-10 23:25:47.697567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09ead0f121b'
down_revision: Union[str, Sequence[str], None] = 'bfc085b2df32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
