"""adicionando is profile complete na users with nullable

Revision ID: c4379ba2b4b6
Revises: c09ead0f121b
Create Date: 2026-06-10 23:29:54.535803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4379ba2b4b6'
down_revision: Union[str, Sequence[str], None] = 'c09ead0f121b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
