name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pytest tests/cinerag.py
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_CINERAG}}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          TMD_CINERAG: ${{ secrets.TMD_KEY}}
